apiVersion: cert-manager.drzzl.io/v1alpha1
kind: KMSIssuer
metadata:
  name: kms-issuer-sample
  namespace: default
spec:
  commonName: Test Root CA
  duration: 87600h # 10 years
  keyId: alias/kms-issuer-example
