apiVersion: cert-manager.drzzl.io/v1alpha1
kind: KMSIssuer
metadata:
  name: kms-issuer-sample
  namespace: default
spec:
  commonName: Test Root CA
  duration: 87600h # 10 years
  keyRef:
    external: projects/my-project/locations/us-central1/keyRings/my-keyring/cryptoKeys/my-key/cryptoKeyVersions/1
