name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '5.4.1'
          kustomize_build_dir: config/default
          kustomize_output_file: rendered/gcp-kms-issuer-installer.yaml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Archive installer resource yaml
        uses: actions/upload-artifact@v4
        with:
          name: gcp-kms-issuer-installer
          path: rendered/gcp-kms-issuer-installer.yaml

  test-build:
    name: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=sha

      - name: Login to GitHub Packages
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish a docker image
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
